name: Deploy to WordPress.org

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    name: Deploy Plugin to WordPress.org SVN
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from tag (strips the "v" prefix)
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Deploy to WordPress.org SVN
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG:         avcl-subscription-interval-repair-for-woocommerce
          VERSION:      ${{ env.VERSION }}
          ASSETS_DIR:   assets
          BUILD_DIR:    trunk
